# Generated by Django 3.1.6 on 2021-03-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
